rvm:
  - 2.2.10
  - 2.3.8
  - 2.6.1
gemfile:
  - gemfiles/Gemfile_rack_1
  - gemfiles/Gemfile_rack_2
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile_rack_2
script: rake test
